- name: SSH KEY ROTATION | Generate keys
  hosts: octo
  vars:
    ssh_key_bits: 2048
    passphrase: 83g!8bfu5M5yy84x
    ssh_key_comment: domain@example.com
    ssh_key_path: '{{ inventory_dir }}/new-ssh-key'
    is_exclusive: yes
    ssh_host_user: vagrant
  tasks:
    - name: Generate a new ssh Key
      command: ssh-keygen
        -t rsa
        -b {{ ssh_key_bits }}
        -N "{{ passphrase }}" -q
        -f {{  ssh_key_path }}
        -C {{ ssh_key_comment }}
      args:
        creates: '{{ ssh_key_path }}'
      delegate_to: localhost

    - name: Store then value of the public ssh key
      set_fact:
        ssh_connection_key: "{{ lookup('file', ssh_key_path + '.pub') }}"

    - name: Set Authorized key(s) to the authorized keys file
      become: yes
      become_user: root
      authorized_key:
        exclusive: '{{ is_exclusive }}'
        user: '{{ ssh_host_user }}'
        state: present
        key: '{{ ssh_connection_key }}'
